import { db, generateLocalId, isLocalId } from '../db/schema';
import type { 
  SyncQueueItem, 
  SyncResult, 
  SyncConflict, 
  Patient, 
  QueueEntry,
  PatientCreate,
  QueueEntryCreate 
} from '@/types';
import { patientsApi } from '@/features/patients/api';
import { queueApi } from '@/features/queue/api';

// ------------------------------------------
// Sync Manager Class
// ------------------------------------------
class SyncManager {
  private syncing = false;
  private retryInterval = 30000; // 30 seconds
  private maxRetries = 5;

  // ------------------------------------------
  // Public Methods
  // ------------------------------------------

  /**
   * Start manual sync process
   */
  async startSync(): Promise<SyncResult> {
    if (this.syncing) {
      return { synced: [], conflicts: [] };
    }

    if (!navigator.onLine) {
      throw new Error('Cannot sync while offline');
    }

    this.syncing = true;
    const results: SyncResult = { synced: [], conflicts: [] };

    try {
      // Get all pending operations ordered by timestamp
      const pending = await db.syncQueue.orderBy('timestamp').toArray();

      for (const operation of pending) {
        try {
          const syncResult = await this.syncOperation(operation);
          
          if (syncResult) {
            results.synced.push(syncResult);
            // Remove from queue on success
            await db.syncQueue.delete(operation.id!);
          }
        } catch (error) {
          await this.handleSyncError(operation, error as Error, results);
        }
      }

      // Update last sync timestamp
      await db.setLastSyncTimestamp();

      return results;
    } finally {
      this.syncing = false;
    }
  }

  /**
   * Auto-sync when coming back online
   */
  startAutoSync(): void {
    // Sync when coming online
    window.addEventListener('online', () => {
      console.log('[SyncManager] Back online, starting sync...');
      this.startSync().catch(console.error);
    });

    // Periodic sync when online
    setInterval(() => {
      if (navigator.onLine && !this.syncing) {
        this.startSync().catch(console.error);
      }
    }, this.retryInterval);
  }

  /**
   * Queue an operation for sync
   */
  async queueOperation(
    operation: 'CREATE' | 'UPDATE' | 'DELETE',
    entity: 'patient' | 'queue' | 'consultation' | 'prescription',
    data: unknown
  ): Promise<void> {
    await db.syncQueue.add({
      operation,
      entity,
      data,
      timestamp: new Date(),
      retryCount: 0,
    });
  }

  /**
   * Create patient with offline support
   */
  async createPatient(patientData: PatientCreate): Promise<Patient> {
    const localId = generateLocalId();
    const patient: Patient = {
      ...patientData,
      id: localId,
      consent_timestamp: new Date().toISOString(),
      is_minor: patientData.age < 18,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      syncStatus: 'pending',
    };

    // Always save to IndexedDB first
    await db.patients.add({ ...patient, syncStatus: 'pending' });

    if (navigator.onLine) {
      try {
        // Try to sync immediately
        const response = await patientsApi.createPatient(patientData);
        
        // Update local record with server data
        await db.patients.update(localId, {
          id: response.id,
          syncStatus: 'synced',
        });

        return { ...patient, id: response.id, syncStatus: 'synced' };
      } catch (error) {
        // Queue for later sync
        await this.queueOperation('CREATE', 'patient', patient);
        return patient;
      }
    } else {
      // Offline: queue for later
      await this.queueOperation('CREATE', 'patient', patient);
      return patient;
    }
  }

  /**
   * Add to queue with offline support
   */
  async addToQueue(queueData: QueueEntryCreate): Promise<QueueEntry> {
    const localId = generateLocalId();
    const entry: QueueEntry = {
      ...queueData,
      id: localId,
      token_number: 'PENDING', // Will be generated by server
      status: 'waiting',
      priority: queueData.priority ?? 0,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
      syncStatus: 'pending',
    };

    // Always save to IndexedDB first
    await db.queue.add({ ...entry, syncStatus: 'pending' });

    if (navigator.onLine) {
      try {
        const response = await queueApi.addToQueue(queueData);
        
        await db.queue.update(localId, {
          id: response.id,
          token_number: response.token_number,
          syncStatus: 'synced',
        });

        return { ...entry, id: response.id, token_number: response.token_number, syncStatus: 'synced' };
      } catch (error) {
        await this.queueOperation('CREATE', 'queue', entry);
        return entry;
      }
    } else {
      await this.queueOperation('CREATE', 'queue', entry);
      return entry;
    }
  }

  /**
   * Update queue status with offline support
   */
  async updateQueueStatus(entryId: string, status: string): Promise<void> {
    const entry = await db.queue.get(entryId);
    if (!entry) {
      throw new Error('Queue entry not found');
    }

    // Update local first
    await db.queue.update(entryId, {
      status: status as QueueEntry['status'],
      updated_at: new Date().toISOString(),
      syncStatus: 'pending',
    });

    if (navigator.onLine && !isLocalId(entryId)) {
      try {
        await queueApi.updateQueueEntry(entryId, { status });
        await db.queue.update(entryId, { syncStatus: 'synced' });
      } catch (error) {
        await this.queueOperation('UPDATE', 'queue', { id: entryId, status });
      }
    } else {
      await this.queueOperation('UPDATE', 'queue', { id: entryId, status });
    }
  }

  /**
   * Get sync status summary
   */
  async getSyncStatus(): Promise<{
    isSyncing: boolean;
    pendingCount: number;
    lastSync: Date | null;
    isOnline: boolean;
  }> {
    const [pendingCount, lastSync] = await Promise.all([
      db.getPendingSyncCount(),
      db.getLastSyncTimestamp(),
    ]);

    return {
      isSyncing: this.syncing,
      pendingCount,
      lastSync,
      isOnline: navigator.onLine,
    };
  }

  // ------------------------------------------
  // Private Methods
  // ------------------------------------------

  private async syncOperation(operation: SyncQueueItem): Promise<{ localId: string; serverId: string; status: string } | null> {
    switch (operation.entity) {
      case 'patient':
        return this.syncPatient(operation);
      case 'queue':
        return this.syncQueue(operation);
      default:
        console.warn(`[SyncManager] Unknown entity: ${operation.entity}`);
        return null;
    }
  }

  private async syncPatient(operation: SyncQueueItem): Promise<{ localId: string; serverId: string; status: string }> {
    const { operation: op, data } = operation as { operation: string; data: Patient };

    if (op === 'CREATE') {
      const response = await patientsApi.createPatient({
        mobile_number: data.mobile_number,
        name: data.name,
        age: data.age,
        gender: data.gender,
        clinic_id: data.clinic_id,
        consent_given: data.consent_given,
      });

      // Update local record
      await db.patients.update(data.id, {
        id: response.id,
        syncStatus: 'synced',
      });

      return { localId: data.id, serverId: response.id, status: 'created' };
    }

    throw new Error(`Unsupported patient operation: ${op}`);
  }

  private async syncQueue(operation: SyncQueueItem): Promise<{ localId: string; serverId: string; status: string }> {
    const { operation: op, data } = operation as { operation: string; data: QueueEntry };

    if (op === 'CREATE') {
      const response = await queueApi.addToQueue({
        clinic_id: data.clinic_id,
        patient_id: data.patient_id,
        priority: data.priority,
        symptoms: data.symptoms,
        bp: data.bp,
        weight: data.weight,
        temperature: data.temperature,
        pulse: data.pulse,
      });

      await db.queue.update(data.id, {
        id: response.id,
        token_number: response.token_number,
        syncStatus: 'synced',
      });

      return { localId: data.id, serverId: response.id, status: 'created' };
    }

    if (op === 'UPDATE') {
      const { id, ...updateData } = data as QueueEntry & { status?: string };
      
      if (isLocalId(id)) {
        // Can't update on server yet, keep in queue
        throw new Error('Local record not yet synced to server');
      }

      await queueApi.updateQueueEntry(id, updateData);
      await db.queue.update(id, { syncStatus: 'synced' });

      return { localId: id, serverId: id, status: 'updated' };
    }

    throw new Error(`Unsupported queue operation: ${op}`);
  }

  private async handleSyncError(
    operation: SyncQueueItem, 
    error: Error, 
    results: SyncResult
  ): Promise<void> {
    const newRetryCount = (operation.retryCount || 0) + 1;

    if (newRetryCount >= this.maxRetries) {
      // Max retries exceeded - mark as error
      results.conflicts.push({
        localId: (operation.data as { id?: string })?.id || 'unknown',
        reason: error.message,
        localData: operation.data,
      });
      
      await db.syncQueue.delete(operation.id!);
    } else {
      // Increment retry count
      await db.syncQueue.update(operation.id!, {
        retryCount: newRetryCount,
        errorMessage: error.message,
      });
    }
  }
}

// ------------------------------------------
// Export Singleton
// ------------------------------------------
export const syncManager = new SyncManager();
